kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-movie-api-mp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-movie-api-mp
  template:
    metadata:
      labels:
        app: helidon-movie-api-mp
    spec:
      containers:
      - name: helidon-movie-api-mp
        image: yny.ocir.io/axiffngjdqvm/movie/helidon-movie-api-mp:{이니셜}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: helidon-movie-api-persistent-storage
          mountPath: /var/lib/volume1
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-port
        - name: DB_SERVICE_NAME
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-service-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: moviedb-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moviedb-secret
              key: password
      volumes:
      - name: helidon-movie-api-persistent-storage
        persistentVolumeClaim:
          claimName: myclaim
      imagePullSecrets:
        - name: ocirsecret
---
kind: Service
apiVersion: v1
metadata:
  name: helidon-movie-api-mp
  labels:
    app: helidon-movie-api-mp
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  ports:
  - port: 30000
    targetPort: 8080
    name: http
  selector:
    app: helidon-movie-api-mp
  type: LoadBalancer
---
